// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

// Login is the dashboard's sign-in page.
//
// ⚠ IT USES A PLAIN <form method="post">, NOT DATASTAR, and that is a decision
// rather than an oversight. Every other view in this package binds inputs to
// datastar signals, and two things make that wrong here:
//
//   - Datastar signals are GLOBAL and every unprefixed one is sent to the
//     backend on every action. A password in a signal is a password sitting in
//     the page's reactive state for as long as the tab is open.
//   - A native form POST works with no JavaScript at all. The one page a locked-
//     out operator needs is the one that should depend on the least.
//
// It also deliberately does not use Layout: that shell renders navigation to
// authenticated pages, and offering links that 401 to someone who has not logged
// in yet is a worse first impression than a page with nothing on it.
func Login(errMsg string, requireTLS bool) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!doctype html><html lang=\"en\"><head><meta charset=\"utf-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1\"><title>Sign in — ocr-router</title><style type=\"text/css\">\n\t\t\t\t{ css }\n\t\t\t\t{ loginCSS }\n\t\t\t</style></head><body><main id=\"main\" class=\"login-wrap\"><div class=\"login-card\"><h1>ocr-router</h1><p class=\"muted\">Administrator sign-in</p>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if requireTLS {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<p class=\"login-error\" role=\"alert\">This page is being served over plain HTTP. The session cookie is marked Secure, so a browser would discard it and the sign-in would appear to succeed and then fail. Put TLS in front of the router before signing in.</p>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		} else {
			if errMsg != "" {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "<p class=\"login-error\" role=\"alert\">")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var2 string
				templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(errMsg)
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/web/views/login.templ`, Line: 44, Col: 51}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "</p>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, " <form method=\"post\" action=\"/admin/login\"><div class=\"field\"><label for=\"email\">Email</label> <input id=\"email\" name=\"email\" type=\"email\" autocomplete=\"username\" required autofocus></div><div class=\"field\"><label for=\"password\">Password</label> <input id=\"password\" name=\"password\" type=\"password\" autocomplete=\"current-password\" required></div><button type=\"submit\">Sign in</button></form>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "<p class=\"muted login-hint\">Sessions last 12 hours and are not extended by use. Signing out ends the session everywhere, including other tabs.</p></div></main></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

// loginCSS is scoped to this page. It is separate from the dashboard's stylesheet
// because the login page is the one view with no navigation, no tables and no
// live region — sharing a layout with them would mean styling around three
// things that are not there.
const loginCSS = `
.login-wrap {
  min-height: 100dvh;
  display: grid;
  place-items: center;
  padding: 1.5rem;
}
.login-card {
  width: 100%;
  max-width: 24rem;
  background: var(--panel);
  border: 1px solid var(--line);
  border-radius: var(--radius);
  padding: 2rem;
}
.login-card h1 { font-size: 1.25rem; margin: 0; }
.login-card > .muted { margin: .25rem 0 1.5rem; }
.login-card .field { margin-bottom: 1rem; }
.login-card label { display: block; margin-bottom: .35rem; font-size: .85rem; }
.login-card input { width: 100%; }
.login-card button { width: 100%; margin-top: .5rem; }
.login-error {
  background: color-mix(in srgb, var(--bad) 12%, transparent);
  border: 1px solid var(--bad);
  border-radius: var(--radius);
  color: var(--text);
  padding: .75rem;
  margin: 0 0 1rem;
  font-size: .9rem;
}
.login-hint { font-size: .8rem; margin: 1.5rem 0 0; }
`

var _ = templruntime.GeneratedTemplate
